program NoK3Tool;

uses
  Forms,
  SysUtils,
  MainWin in 'MainWin.pas' {frmMain},
  HWCinSumWin in 'HWCinSumWin.pas' {frmHWCinSum},
  CommUtils in 'CommUtils.pas',
  MrpPRMergeWin in 'MrpPRMergeWin.pas' {frmMrpPRMerge},
  SOPAchievementWin in 'SOPAchievementWin.pas' {frmSOPAchievement},
  MergePlansWin in 'MergePlansWin.pas' {frmMergePlans},
  MergePlansAnalysisWin2 in 'MergePlansAnalysisWin2.pas' {frmMergePlansAnalysis2},
  SOPVSActWin in 'SOPVSActWin.pas' {frmSOPVSAct},
  SOPReaderUnit in 'SOPReaderUnit.pas',
  SOPVSActReaderUnit in 'SOPVSActReaderUnit.pas',
  BSFormatWin in 'BSFormatWin.pas' {frmBSFormat},
  BSDemandReader in 'BSDemandReader.pas',
  FGDemandWin in 'FGDemandWin.pas' {frmFGDemand},
  LocalFGDemandWin in 'LocalFGDemandWin.pas' {frmLocalFGDemand},
  ProjNameNoWin in 'ProjNameNoWin.pas' {frmProjNameNo},
  SelectFGDemandWin in 'SelectFGDemandWin.pas' {frmSelectFGDemand},
  DailyPlanVsActReader in 'DailyPlanVsActReader.pas',
  MPACompareWin in 'MPACompareWin.pas' {frmMPACompare},
  DataIntAnalysisReader in 'DataIntAnalysisReader.pas',
  WaterfallWin2 in 'WaterfallWin2.pas' {frmWaterfall2},
  ManMrpWin in 'ManMrpWin.pas' {frmManMrp},
  DataIntMergeWin in 'DataIntMergeWin.pas' {frmDataIntMerge},
  FGDemandConfigWin in 'FGDemandConfigWin.pas' {frmFGDemandConfig},
  DBConfigWin in 'DBConfigWin.pas' {frmDBConfig},
  ExcelConsts in 'ExcelConsts.pas',
  FGDemandManageWin in 'FGDemandManageWin.pas' {frmFGDemandManage},
  SOPvsMPSWin in 'SOPvsMPSWin.pas' {frmSOPvsMPS},
  KeyICItemSupplyReader in '..\dev\K3Tool\KeyICItemSupplyReader.pas',
  SBomReader in 'SBomReader.pas',
  SOPSimReader in 'SOPSimReader.pas',
  MrpMPSReader in 'MrpMPSReader.pas',
  SopSimSumWin in 'SopSimSumWin.pas' {frmSopSimSum},
  NewSKUReader in 'NewSKUReader.pas',
  DOSReader in 'DOSReader.pas',
  FGPriorityReader in 'FGPriorityReader.pas',
  DOSPlanReader in 'DOSPlanReader.pas',
  StockBalReader in 'StockBalReader.pas',
  SEOutReader in 'SEOutReader.pas',
  ScheActExceptionWin in 'ScheActExceptionWin.pas' {frmScheActException},
  ProjOfICItemWin in 'ProjOfICItemWin.pas' {frmProjOfICItem},
  SOP2PPOrderWin in 'SOP2PPOrderWin.pas' {frmSOP2PPOrder},
  HWPkgStuffWin in 'HWPkgStuffWin.pas' {frmHWPkgStuff},
  FGTableReader in '..\dev\K3Tool\FGTableReader.pas',
  FGStockReader in '..\dev\K3Tool\FGStockReader.pas',
  WaterfallWin in 'WaterfallWin.pas' {frmWaterfall},
  SAP2SOPWin in 'SAP2SOPWin.pas' {frmSAP2SOP},
  SWaterfall in 'SWaterfall.pas' {frmSWaterfall},
  SWaterfallReader in 'SWaterfallReader.pas',
  SOP2SAPWin in 'SOP2SAPWin.pas' {frmSOP2SAP},
  SAPS618Reader in 'SAPS618Reader.pas',
  LTPCMSConfirmReader in 'LTPCMSConfirmReader.pas',
  SAPBomReader in 'SAPBomReader.pas',
  SAPStockReader in 'SAPStockReader.pas',
  SAPBom2SBomWin in 'SAPBom2SBomWin.pas' {frmSAPBom2SBom},
  LTP_CMS2MRPSimWin in 'LTP_CMS2MRPSimWin.pas' {frmLTP_CMS2MRPSim},
  MRPSimulationWin in 'MRPSimulationWin.pas' {frmMRPSimulation},
  MakeFGReportWin2 in 'MakeFGReportWin2.pas' {frmMakeFGReport2},
  FGUnOutRptReader in 'FGUnOutRptReader.pas',
  FGWinReader in 'FGWinReader.pas',
  FGStockRptReader in 'FGStockRptReader.pas',
  FGDBRptReader in 'FGDBRptReader.pas',
  ProjYearWin in 'ProjYearWin.pas' {frmProjYear},
  MakeFGReportCommon in 'MakeFGReportCommon.pas',
  FGRptWinReader in 'FGRptWinReader.pas',
  MRP4SAPWin3_MRP2 in 'MRP4SAPWin3_MRP2.pas' {frmMRP4SAP3_MRP2},
  MRP4SAPWin3_MRP in 'MRP4SAPWin3_MRP.pas' {frmMRP4SAP3_MRP},
  SAPOPOReader in 'SAPOPOReader.pas',
  SAPMaterialReader in 'SAPMaterialReader.pas',
  SAPBomReader2 in 'SAPBomReader2.pas',
  SAPBomReader3 in 'SAPBomReader3.pas',
  SAPStockReader2 in 'SAPStockReader2.pas',
  SAPOPOReader2 in 'SAPOPOReader2.pas',
  SAPMaterialReader2 in 'SAPMaterialReader2.pas',
  SOPVerCompareWin in 'SOPVerCompareWin.pas' {frmSOPVerCompare},
  SAPHW90Reader in 'SAPHW90Reader.pas',
  MRP4SAPWin in 'MRP4SAPWin.pas' {frmMRP4SAP},
  SAPMrpAreaStockReader in 'SAPMrpAreaStockReader.pas',
  FacAccountCheckWin in 'FacAccountCheckWin.pas' {frmFacAccountCheck},
  SAPMB51Reader2 in 'SAPMB51Reader2.pas',
  SAPCMSPushErrorReader2 in 'SAPCMSPushErrorReader2.pas',
  SAPDailyAccountReader2 in 'SAPDailyAccountReader2.pas',
  StockMZ2FacReader in 'StockMZ2FacReader.pas',
  MergePlansAnalysisWin in 'MergePlansAnalysisWin.pas' {frmMergePlansAnalysis},
  CPInAndStockWin in 'CPInAndStockWin.pas' {frmCPInAndStock},
  CPInAndStockReader in 'CPInAndStockReader.pas',
  MRPAreaStockCheckWin in 'MRPAreaStockCheckWin.pas' {frmMRPAreaStockCheck},
  StockListReader in 'StockListReader.pas',
  SAPImportS620Reader in 'SAPImportS620Reader.pas',
  MergeS620ImportTemplateWin in 'MergeS620ImportTemplateWin.pas' {frmMergeS620ImportTemplate},
  XHBomLocation2RowWin in 'XHBomLocation2RowWin.pas' {frmXHBomLocation2Row},
  XHBomReader in 'XHBomReader.pas',
  SAPBomMatrixWin in 'SAPBomMatrixWin.pas' {frmSAPBomMatrix},
  ProjNameReader in 'ProjNameReader.pas',
  BomD2Reader2 in 'BomD2Reader2.pas',
  MRP4SAPWin2_CTB in 'MRP4SAPWin2_CTB.pas' {frmMRP4SAP2_CTB},
  ICMO2FacReader in 'ICMO2FacReader.pas',
  MakeFGReportWin in 'MakeFGReportWin.pas' {frmMakeFGReport},
  SAPWhereUseReader in 'SAPWhereUseReader.pas',
  SubstractMrpLogWin in 'SubstractMrpLogWin.pas' {frmSubstractMrpLog},
  MrpLogReader2 in 'MrpLogReader2.pas',
  SalePlanWin in 'SalePlanWin.pas' {frmSalePlan},
  FGAll2MZMBWin in 'FGAll2MZMBWin.pas' {frmFGAll2MZMB},
  BomD2Reader in 'BomD2Reader.pas',
  MergeBomWin in 'MergeBomWin.pas' {frmMergeBom},
  ExcelUnit in 'ExcelUnit.pas',
  CommVars in 'CommVars.pas',
  MrpSimDemandWin in 'MrpSimDemandWin.pas' {frmMrpSimDemand},
  ManMrpReader in 'ManMrpReader.pas',
  SimMPSReader in 'SimMPSReader.pas',
  SalePlanWFWin in 'SalePlanWFWin.pas' {frmSalePlanWF},
  SalePlanWFReader in 'SalePlanWFReader.pas',
  RawMPSReader in 'RawMPSReader.pas',
  NumberCheckReader in 'NumberCheckReader.pas',
  ExcelBomReader in 'ExcelBomReader.pas',
  Excel2MrpBomWin in 'Excel2MrpBomWin.pas' {frmExcel2MrpBom},
  WhereUseWin in 'WhereUseWin.pas' {frmWhereUse},
  SOPSumWin in 'SOPSumWin.pas' {frmSOPSum},
  ZMDR001Reader in 'ZMDR001Reader.pas',
  BomAllocCheckWin in 'BomAllocCheckWin.pas' {frmBomAllocCheck},
  FGToProduceReader in 'FGToProduceReader.pas',
  HWOrdInfoReader in 'HWOrdInfoReader.pas',
  PCNumberWin in 'PCNumberWin.pas' {frmPCNumber},
  KittingWin in 'KittingWin.pas' {frmKitting},
  KittingPPReader in 'KittingPPReader.pas',
  KittingKeyNumberReader in 'KittingKeyNumberReader.pas';

{$R *.res}

begin
  DateSeparator := '-';
  Application.Initialize;
  TfrmDBConfig.Load;
  Application.CreateForm(TfrmMain, frmMain);
  Application.Run;
end.
